# Generated by Django 5.1.5 on 2025-04-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_job_apply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='submitted_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills, e.g., Python, Django, SQL'),
        ),
    ]
