# Generated by Django 5.1.5 on 2025-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_applicant_submitted_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default='', help_text='Comma-separated skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_match_threshold',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='submitted_skills',
            field=models.TextField(default='', help_text='Comma-separated skills'),
        ),
    ]
