# Generated by Django 5.1.5 on 2025-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_job_required_skills_job_skill_match_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='meeting_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
