# Generated by Django 5.1.5 on 2025-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0011_applicant_meeting_link_applicant_meeting_link_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skill_match_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
